ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;  

SELECT NOMBRE, GRADO_ALCOHOL
FROM PARRANDEROS.BEBIDAS
WHERE GRADO_ALCOHOL > 9 AND NOT (NOMBRE LIKE '%bebida%');

SELECT CIUDAD
FROM BARES
GROUP BY CIUDAD
HAVING SUM(CANT_SEDES) > 30 AND SUM(CANT_SEDES) < 50 AND COUNT(*) >= 6;

SELECT NOMBRE, ID
FROM BARES 
INNER JOIN BARES.SIRVEN ON (BARES.ID)
FETCH FIRST 10 ROWS ONLY;



